name: Greet

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    paths:
      - greetings.md

jobs:
  greet:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: greet someone
        run: echo "${{ vars.GREETING }}"
