name: greet on main

on:
  push:
    branches:
      - main

jobs:
  greet:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: greet someone
        run: echo "${{ vars.GREETING }}"
