name: greet on main

on:
  push:
    branches:
      - main

jobs:
  greet_staging:
    uses: ./.github/workflows/_greet.yml
    with:
      environment: staging

  greet_prod:
    needs: greet_staging
    uses: ./.github/workflows/_greet.yml
    with:
      environment: prod
